<?php

namespace Database\Seeders;

use App\Models\KodeTemuan;
use Illuminate\Database\Seeder;

/**
 * KodeTemuanSeeder
 *
 * Sumber: PermenPAN No. 42 Tahun 2011
 *         Lampiran 2.1 — Kode Atribut Temuan Audit
 *
 * Struktur kode: {kel}.{sub_kel}.{jenis}
 * Contoh: 1.01.05 = Kel 1 (Ketidakpatuhan), Sub Kel 01 (Kerugian), Jenis 05 (Pemahalan Harga)
 *
 * Total: 56 kode temuan resmi
 *
 * Kelompok:
 *   1 = Temuan Ketidakpatuhan Terhadap Peraturan
 *   2 = Temuan Kelemahan Sistem Pengendalian Intern (SPI)
 *   3 = Temuan 3E (Ekonomis, Efisien, Efektif)
 */
class KodeTemuanSeeder extends Seeder
{
    public function run(): void
    {
        $data = $this->getData();

        foreach ($data as $item) {
            KodeTemuan::updateOrCreate(
                ['kode' => $item['kode']],
                $item
            );
        }

        $total = count($data);
        $this->command->info("✅ KodeTemuanSeeder: {$total} kode berhasil di-seed.");
    }

    private function getData(): array
    {
        return [
            // ════════════════════════════════════════════════════════════════
            // KELOMPOK 1 — TEMUAN KETIDAKPATUHAN TERHADAP PERATURAN
            // ════════════════════════════════════════════════════════════════

            // ── Sub Kelompok 01: Kerugian Negara/Daerah ───────────────────
            [
                'kode'         => '1.01.01',
                'kode_numerik' => '1.01.01',
                'kel'          => 1,
                'sub_kel'      => 1,
                'jenis'        => 1,
                'kelompok'     => 'Temuan Ketidakpatuhan Terhadap Peraturan',
                'sub_kelompok' => 'Kerugian negara/daerah atau kerugian negara/daerah yang terjadi pada perusahaan milik negara/daerah',
                'deskripsi'    => 'Belanja dan/atau pengadaan barang/jasa fiktif',
                'alternatif_rekom' => [1, 5, 9, 11, 12],
            ],
            [
                'kode'         => '1.01.02',
                'kode_numerik' => '1.01.02',
                'kel'          => 1,
                'sub_kel'      => 1,
                'jenis'        => 2,
                'kelompok'     => 'Temuan Ketidakpatuhan Terhadap Peraturan',
                'sub_kelompok' => 'Kerugian negara/daerah atau kerugian negara/daerah yang terjadi pada perusahaan milik negara/daerah',
                'deskripsi'    => 'Rekanan pengadaan barang/jasa tidak menyelesaikan pekerjaan',
                'alternatif_rekom' => [1, 3, 11, 12],
            ],
            [
                'kode'         => '1.01.03',
                'kode_numerik' => '1.01.03',
                'kel'          => 1,
                'sub_kel'      => 1,
                'jenis'        => 3,
                'kelompok'     => 'Temuan Ketidakpatuhan Terhadap Peraturan',
                'sub_kelompok' => 'Kerugian negara/daerah atau kerugian negara/daerah yang terjadi pada perusahaan milik negara/daerah',
                'deskripsi'    => 'Kekurangan volume pekerjaan dan/atau barang',
                'alternatif_rekom' => [1, 3, 5, 9, 11, 12],
            ],
            [
                'kode'         => '1.01.04',
                'kode_numerik' => '1.01.04',
                'kel'          => 1,
                'sub_kel'      => 1,
                'jenis'        => 4,
                'kelompok'     => 'Temuan Ketidakpatuhan Terhadap Peraturan',
                'sub_kelompok' => 'Kerugian negara/daerah atau kerugian negara/daerah yang terjadi pada perusahaan milik negara/daerah',
                'deskripsi'    => 'Kelebihan pembayaran selain kekurangan volume pekerjaan dan/atau barang',
                'alternatif_rekom' => [1, 3, 5, 9, 11, 12],
            ],
            [
                'kode'         => '1.01.05',
                'kode_numerik' => '1.01.05',
                'kel'          => 1,
                'sub_kel'      => 1,
                'jenis'        => 5,
                'kelompok'     => 'Temuan Ketidakpatuhan Terhadap Peraturan',
                'sub_kelompok' => 'Kerugian negara/daerah atau kerugian negara/daerah yang terjadi pada perusahaan milik negara/daerah',
                'deskripsi'    => 'Pemahalan harga (Mark up)',
                'alternatif_rekom' => [1, 5, 9, 11, 12],
            ],
            [
                'kode'         => '1.01.06',
                'kode_numerik' => '1.01.06',
                'kel'          => 1,
                'sub_kel'      => 1,
                'jenis'        => 6,
                'kelompok'     => 'Temuan Ketidakpatuhan Terhadap Peraturan',
                'sub_kelompok' => 'Kerugian negara/daerah atau kerugian negara/daerah yang terjadi pada perusahaan milik negara/daerah',
                'deskripsi'    => 'Penggunaan uang/barang untuk kepentingan pribadi',
                'alternatif_rekom' => [1, 2, 5, 9, 11, 12],
            ],
            [
                'kode'         => '1.01.07',
                'kode_numerik' => '1.01.07',
                'kel'          => 1,
                'sub_kel'      => 1,
                'jenis'        => 7,
                'kelompok'     => 'Temuan Ketidakpatuhan Terhadap Peraturan',
                'sub_kelompok' => 'Kerugian negara/daerah atau kerugian negara/daerah yang terjadi pada perusahaan milik negara/daerah',
                'deskripsi'    => 'Pembayaran honorarium dan/atau biaya perjalanan dinas ganda dan/atau melebihi standar yang ditetapkan',
                'alternatif_rekom' => [1, 5, 9, 11, 12],
            ],
            [
                'kode'         => '1.01.08',
                'kode_numerik' => '1.01.08',
                'kel'          => 1,
                'sub_kel'      => 1,
                'jenis'        => 8,
                'kelompok'     => 'Temuan Ketidakpatuhan Terhadap Peraturan',
                'sub_kelompok' => 'Kerugian negara/daerah atau kerugian negara/daerah yang terjadi pada perusahaan milik negara/daerah',
                'deskripsi'    => 'Spesifikasi barang/jasa yang diterima tidak sesuai dengan kontrak',
                'alternatif_rekom' => [1, 3, 5, 11, 12],
            ],
            [
                'kode'         => '1.01.09',
                'kode_numerik' => '1.01.09',
                'kel'          => 1,
                'sub_kel'      => 1,
                'jenis'        => 9,
                'kelompok'     => 'Temuan Ketidakpatuhan Terhadap Peraturan',
                'sub_kelompok' => 'Kerugian negara/daerah atau kerugian negara/daerah yang terjadi pada perusahaan milik negara/daerah',
                'deskripsi'    => 'Belanja tidak sesuai atau melebihi ketentuan',
                'alternatif_rekom' => [1, 5, 9, 11, 12],
            ],
            [
                'kode'         => '1.01.10',
                'kode_numerik' => '1.01.10',
                'kel'          => 1,
                'sub_kel'      => 1,
                'jenis'        => 10,
                'kelompok'     => 'Temuan Ketidakpatuhan Terhadap Peraturan',
                'sub_kelompok' => 'Kerugian negara/daerah atau kerugian negara/daerah yang terjadi pada perusahaan milik negara/daerah',
                'deskripsi'    => 'Pengembalian pinjaman/piutang atau dana bergulir macet',
                'alternatif_rekom' => [1, 5, 9, 11, 12],
            ],
            [
                'kode'         => '1.01.11',
                'kode_numerik' => '1.01.11',
                'kel'          => 1,
                'sub_kel'      => 1,
                'jenis'        => 11,
                'kelompok'     => 'Temuan Ketidakpatuhan Terhadap Peraturan',
                'sub_kelompok' => 'Kerugian negara/daerah atau kerugian negara/daerah yang terjadi pada perusahaan milik negara/daerah',
                'deskripsi'    => 'Kelebihan penetapan dan pembayaran restitusi pajak atau penetapan kompensasi kerugian',
                'alternatif_rekom' => [1, 5, 9, 11, 12],
            ],
            [
                'kode'         => '1.01.12',
                'kode_numerik' => '1.01.12',
                'kel'          => 1,
                'sub_kel'      => 1,
                'jenis'        => 12,
                'kelompok'     => 'Temuan Ketidakpatuhan Terhadap Peraturan',
                'sub_kelompok' => 'Kerugian negara/daerah atau kerugian negara/daerah yang terjadi pada perusahaan milik negara/daerah',
                'deskripsi'    => 'Penjualan/pertukaran/penghapusan aset negara/daerah tidak sesuai ketentuan dan merugikan negara/daerah',
                'alternatif_rekom' => [1, 5, 9, 11, 12],
            ],
            [
                'kode'         => '1.01.13',
                'kode_numerik' => '1.01.13',
                'kel'          => 1,
                'sub_kel'      => 1,
                'jenis'        => 13,
                'kelompok'     => 'Temuan Ketidakpatuhan Terhadap Peraturan',
                'sub_kelompok' => 'Kerugian negara/daerah atau kerugian negara/daerah yang terjadi pada perusahaan milik negara/daerah',
                'deskripsi'    => 'Pengenaan ganti kerugian negara belum/tidak dilaksanakan sesuai ketentuan',
                'alternatif_rekom' => [1, 2, 3, 5, 9, 11, 12],
            ],
            [
                'kode'         => '1.01.14',
                'kode_numerik' => '1.01.14',
                'kel'          => 1,
                'sub_kel'      => 1,
                'jenis'        => 14,
                'kelompok'     => 'Temuan Ketidakpatuhan Terhadap Peraturan',
                'sub_kelompok' => 'Kerugian negara/daerah atau kerugian negara/daerah yang terjadi pada perusahaan milik negara/daerah',
                'deskripsi'    => 'Entitas belum/tidak melaksanakan tuntutan perbendaharaan (TP) sesuai ketentuan',
                'alternatif_rekom' => [1, 2, 3, 5, 9, 11, 12],
            ],
            [
                'kode'         => '1.01.15',
                'kode_numerik' => '1.01.15',
                'kel'          => 1,
                'sub_kel'      => 1,
                'jenis'        => 15,
                'kelompok'     => 'Temuan Ketidakpatuhan Terhadap Peraturan',
                'sub_kelompok' => 'Kerugian negara/daerah atau kerugian negara/daerah yang terjadi pada perusahaan milik negara/daerah',
                'deskripsi'    => 'Penghapusan hak tagih tidak sesuai ketentuan',
                'alternatif_rekom' => [1, 5, 7, 9, 11, 12],
            ],
            [
                'kode'         => '1.01.16',
                'kode_numerik' => '1.01.16',
                'kel'          => 1,
                'sub_kel'      => 1,
                'jenis'        => 16,
                'kelompok'     => 'Temuan Ketidakpatuhan Terhadap Peraturan',
                'sub_kelompok' => 'Kerugian negara/daerah atau kerugian negara/daerah yang terjadi pada perusahaan milik negara/daerah',
                'deskripsi'    => 'Pelanggaran ketentuan pemberian diskon penjualan',
                'alternatif_rekom' => [1, 5, 9, 11, 12],
            ],
            [
                'kode'         => '1.01.17',
                'kode_numerik' => '1.01.17',
                'kel'          => 1,
                'sub_kel'      => 1,
                'jenis'        => 17,
                'kelompok'     => 'Temuan Ketidakpatuhan Terhadap Peraturan',
                'sub_kelompok' => 'Kerugian negara/daerah atau kerugian negara/daerah yang terjadi pada perusahaan milik negara/daerah',
                'deskripsi'    => 'Penentuan HPP (harga pokok pembelian) terlalu rendah sehingga penentuan harga jual lebih rendah dari yang seharusnya',
                'alternatif_rekom' => [1, 5, 9, 11, 12],
            ],
            [
                'kode'         => '1.01.18',
                'kode_numerik' => '1.01.18',
                'kel'          => 1,
                'sub_kel'      => 1,
                'jenis'        => 18,
                'kelompok'     => 'Temuan Ketidakpatuhan Terhadap Peraturan',
                'sub_kelompok' => 'Kerugian negara/daerah atau kerugian negara/daerah yang terjadi pada perusahaan milik negara/daerah',
                'deskripsi'    => 'Jaminan pelaksanaan dalam pelaksanaan pekerjaan, pemanfaatan barang dan pemberian fasilitas tidak dapat dicairkan',
                'alternatif_rekom' => [1, 5, 9, 11, 12],
            ],
            [
                'kode'         => '1.01.19',
                'kode_numerik' => '1.01.19',
                'kel'          => 1,
                'sub_kel'      => 1,
                'jenis'        => 19,
                'kelompok'     => 'Temuan Ketidakpatuhan Terhadap Peraturan',
                'sub_kelompok' => 'Kerugian negara/daerah atau kerugian negara/daerah yang terjadi pada perusahaan milik negara/daerah',
                'deskripsi'    => 'Penyetoran penerimaan negara/daerah dengan bukti fiktif',
                'alternatif_rekom' => [1, 5, 9, 11, 12],
            ],

            // ── Sub Kelompok 02: Potensi Kerugian ────────────────────────
            [
                'kode'         => '1.02.01',
                'kode_numerik' => '1.02.01',
                'kel'          => 1,
                'sub_kel'      => 2,
                'jenis'        => 1,
                'kelompok'     => 'Temuan Ketidakpatuhan Terhadap Peraturan',
                'sub_kelompok' => 'Potensi kerugian negara/daerah atau kerugian negara/daerah yang terjadi pada perusahaan milik negara/daerah',
                'deskripsi'    => 'Kelebihan pembayaran dalam pengadaan barang/jasa tetapi pembayaran pekerjaan belum dilakukan sebagian atau seluruhnya',
                'alternatif_rekom' => [5, 9, 12],
            ],
            [
                'kode'         => '1.02.02',
                'kode_numerik' => '1.02.02',
                'kel'          => 1,
                'sub_kel'      => 2,
                'jenis'        => 2,
                'kelompok'     => 'Temuan Ketidakpatuhan Terhadap Peraturan',
                'sub_kelompok' => 'Potensi kerugian negara/daerah atau kerugian negara/daerah yang terjadi pada perusahaan milik negara/daerah',
                'deskripsi'    => 'Rekanan belum melaksanakan kewajiban pemeliharaan barang hasil pengadaan yang telah rusak selama masa pemeliharaan',
                'alternatif_rekom' => [3, 6, 9, 12],
            ],
            [
                'kode'         => '1.02.03',
                'kode_numerik' => '1.02.03',
                'kel'          => 1,
                'sub_kel'      => 2,
                'jenis'        => 3,
                'kelompok'     => 'Temuan Ketidakpatuhan Terhadap Peraturan',
                'sub_kelompok' => 'Potensi kerugian negara/daerah atau kerugian negara/daerah yang terjadi pada perusahaan milik negara/daerah',
                'deskripsi'    => 'Aset dikuasai pihak lain',
                'alternatif_rekom' => [2, 5, 6, 9, 12],
            ],
            [
                'kode'         => '1.02.04',
                'kode_numerik' => '1.02.04',
                'kel'          => 1,
                'sub_kel'      => 2,
                'jenis'        => 4,
                'kelompok'     => 'Temuan Ketidakpatuhan Terhadap Peraturan',
                'sub_kelompok' => 'Potensi kerugian negara/daerah atau kerugian negara/daerah yang terjadi pada perusahaan milik negara/daerah',
                'deskripsi'    => 'Pembelian aset yang berstatus sengketa',
                'alternatif_rekom' => [5, 6, 9, 12],
            ],
            [
                'kode'         => '1.02.05',
                'kode_numerik' => '1.02.05',
                'kel'          => 1,
                'sub_kel'      => 2,
                'jenis'        => 5,
                'kelompok'     => 'Temuan Ketidakpatuhan Terhadap Peraturan',
                'sub_kelompok' => 'Potensi kerugian negara/daerah atau kerugian negara/daerah yang terjadi pada perusahaan milik negara/daerah',
                'deskripsi'    => 'Aset tidak diketahui keberadaannya',
                'alternatif_rekom' => [2, 5, 6, 9, 12],
            ],
            [
                'kode'         => '1.02.06',
                'kode_numerik' => '1.02.06',
                'kel'          => 1,
                'sub_kel'      => 2,
                'jenis'        => 6,
                'kelompok'     => 'Temuan Ketidakpatuhan Terhadap Peraturan',
                'sub_kelompok' => 'Potensi kerugian negara/daerah atau kerugian negara/daerah yang terjadi pada perusahaan milik negara/daerah',
                'deskripsi'    => 'Pemberian jaminan pelaksanaan dalam pelaksanaan pekerjaan, pemanfaatan barang dan pemberian fasilitas tidak sesuai ketentuan',
                'alternatif_rekom' => [5, 6, 9, 12],
            ],
            [
                'kode'         => '1.02.07',
                'kode_numerik' => '1.02.07',
                'kel'          => 1,
                'sub_kel'      => 2,
                'jenis'        => 7,
                'kelompok'     => 'Temuan Ketidakpatuhan Terhadap Peraturan',
                'sub_kelompok' => 'Potensi kerugian negara/daerah atau kerugian negara/daerah yang terjadi pada perusahaan milik negara/daerah',
                'deskripsi'    => 'Pihak ketiga belum melaksanakan kewajiban untuk menyerahkan aset kepada negara/daerah',
                'alternatif_rekom' => [5, 6, 9, 12],
            ],
            [
                'kode'         => '1.02.08',
                'kode_numerik' => '1.02.08',
                'kel'          => 1,
                'sub_kel'      => 2,
                'jenis'        => 8,
                'kelompok'     => 'Temuan Ketidakpatuhan Terhadap Peraturan',
                'sub_kelompok' => 'Potensi kerugian negara/daerah atau kerugian negara/daerah yang terjadi pada perusahaan milik negara/daerah',
                'deskripsi'    => 'Piutang/pinjaman atau dana bergulir yang berpotensi tidak tertagih',
                'alternatif_rekom' => [5, 9, 12],
            ],
            [
                'kode'         => '1.02.09',
                'kode_numerik' => '1.02.09',
                'kel'          => 1,
                'sub_kel'      => 2,
                'jenis'        => 9,
                'kelompok'     => 'Temuan Ketidakpatuhan Terhadap Peraturan',
                'sub_kelompok' => 'Potensi kerugian negara/daerah atau kerugian negara/daerah yang terjadi pada perusahaan milik negara/daerah',
                'deskripsi'    => 'Penghapusan piutang tidak sesuai ketentuan',
                'alternatif_rekom' => [5, 7, 9, 11, 12],
            ],
            [
                'kode'         => '1.02.10',
                'kode_numerik' => '1.02.10',
                'kel'          => 1,
                'sub_kel'      => 2,
                'jenis'        => 10,
                'kelompok'     => 'Temuan Ketidakpatuhan Terhadap Peraturan',
                'sub_kelompok' => 'Potensi kerugian negara/daerah atau kerugian negara/daerah yang terjadi pada perusahaan milik negara/daerah',
                'deskripsi'    => 'Pencairan anggaran pada akhir tahun anggaran untuk pekerjaan yang belum selesai',
                'alternatif_rekom' => [1, 3, 5, 9, 11, 12],
            ],

            // ── Sub Kelompok 03: Kekurangan Penerimaan ───────────────────
            [
                'kode'         => '1.03.01',
                'kode_numerik' => '1.03.01',
                'kel'          => 1,
                'sub_kel'      => 3,
                'jenis'        => 1,
                'kelompok'     => 'Temuan Ketidakpatuhan Terhadap Peraturan',
                'sub_kelompok' => 'Kekurangan penerimaan negara/daerah atau perusahaan milik negara/daerah',
                'deskripsi'    => 'Penerimaan negara/daerah atau denda keterlambatan pekerjaan belum/tidak ditetapkan dipungut/diterima/disetor ke kas negara/daerah atau perusahaan milik negara/daerah',
                'alternatif_rekom' => [1, 5, 9, 11, 12],
            ],
            [
                'kode'         => '1.03.02',
                'kode_numerik' => '1.03.02',
                'kel'          => 1,
                'sub_kel'      => 3,
                'jenis'        => 2,
                'kelompok'     => 'Temuan Ketidakpatuhan Terhadap Peraturan',
                'sub_kelompok' => 'Kekurangan penerimaan negara/daerah atau perusahaan milik negara/daerah',
                'deskripsi'    => 'Penggunaan langsung penerimaan negara/daerah',
                'alternatif_rekom' => [5, 6, 9, 12],
            ],
            [
                'kode'         => '1.03.03',
                'kode_numerik' => '1.03.03',
                'kel'          => 1,
                'sub_kel'      => 3,
                'jenis'        => 3,
                'kelompok'     => 'Temuan Ketidakpatuhan Terhadap Peraturan',
                'sub_kelompok' => 'Kekurangan penerimaan negara/daerah atau perusahaan milik negara/daerah',
                'deskripsi'    => 'Dana Perimbangan yang telah ditetapkan belum masuk ke kas daerah',
                'alternatif_rekom' => [1, 5, 6, 9, 12],
            ],
            [
                'kode'         => '1.03.04',
                'kode_numerik' => '1.03.04',
                'kel'          => 1,
                'sub_kel'      => 3,
                'jenis'        => 4,
                'kelompok'     => 'Temuan Ketidakpatuhan Terhadap Peraturan',
                'sub_kelompok' => 'Kekurangan penerimaan negara/daerah atau perusahaan milik negara/daerah',
                'deskripsi'    => 'Penerimaan negara/daerah diterima atau digunakan oleh instansi yang tidak berhak',
                'alternatif_rekom' => [1, 5, 6, 9, 11, 12],
            ],
            [
                'kode'         => '1.03.05',
                'kode_numerik' => '1.03.05',
                'kel'          => 1,
                'sub_kel'      => 3,
                'jenis'        => 5,
                'kelompok'     => 'Temuan Ketidakpatuhan Terhadap Peraturan',
                'sub_kelompok' => 'Kekurangan penerimaan negara/daerah atau perusahaan milik negara/daerah',
                'deskripsi'    => 'Pengenaan tarif pajak/PNBP lebih rendah dari ketentuan',
                'alternatif_rekom' => [1, 5, 6, 9, 12],
            ],
            [
                'kode'         => '1.03.06',
                'kode_numerik' => '1.03.06',
                'kel'          => 1,
                'sub_kel'      => 3,
                'jenis'        => 6,
                'kelompok'     => 'Temuan Ketidakpatuhan Terhadap Peraturan',
                'sub_kelompok' => 'Kekurangan penerimaan negara/daerah atau perusahaan milik negara/daerah',
                'deskripsi'    => 'Koreksi perhitungan bagi hasil dengan KKKS',
                'alternatif_rekom' => [1, 5, 6, 9, 12],
            ],
            [
                'kode'         => '1.03.07',
                'kode_numerik' => '1.03.07',
                'kel'          => 1,
                'sub_kel'      => 3,
                'jenis'        => 7,
                'kelompok'     => 'Temuan Ketidakpatuhan Terhadap Peraturan',
                'sub_kelompok' => 'Kekurangan penerimaan negara/daerah atau perusahaan milik negara/daerah',
                'deskripsi'    => 'Kelebihan pembayaran subsidi oleh pemerintah',
                'alternatif_rekom' => [1, 5, 6, 9, 12],
            ],

            // ── Sub Kelompok 04: Administrasi ────────────────────────────
            [
                'kode'         => '1.04.01',
                'kode_numerik' => '1.04.01',
                'kel'          => 1,
                'sub_kel'      => 4,
                'jenis'        => 1,
                'kelompok'     => 'Temuan Ketidakpatuhan Terhadap Peraturan',
                'sub_kelompok' => 'Administrasi',
                'deskripsi'    => 'Pertanggungjawaban tidak akuntabel (bukti tidak lengkap/tidak valid)',
                'alternatif_rekom' => [5, 6, 9, 12],
            ],
            [
                'kode'         => '1.04.02',
                'kode_numerik' => '1.04.02',
                'kel'          => 1,
                'sub_kel'      => 4,
                'jenis'        => 2,
                'kelompok'     => 'Temuan Ketidakpatuhan Terhadap Peraturan',
                'sub_kelompok' => 'Administrasi',
                'deskripsi'    => 'Pekerjaan dilaksanakan mendahului kontrak atau penetapan anggaran',
                'alternatif_rekom' => [5, 9, 12],
            ],
            [
                'kode'         => '1.04.03',
                'kode_numerik' => '1.04.03',
                'kel'          => 1,
                'sub_kel'      => 4,
                'jenis'        => 3,
                'kelompok'     => 'Temuan Ketidakpatuhan Terhadap Peraturan',
                'sub_kelompok' => 'Administrasi',
                'deskripsi'    => 'Proses pengadaan barang/jasa tidak sesuai ketentuan (tidak menimbulkan kerugian negara)',
                'alternatif_rekom' => [5, 6, 9, 13],
            ],
            [
                'kode'         => '1.04.04',
                'kode_numerik' => '1.04.04',
                'kel'          => 1,
                'sub_kel'      => 4,
                'jenis'        => 4,
                'kelompok'     => 'Temuan Ketidakpatuhan Terhadap Peraturan',
                'sub_kelompok' => 'Administrasi',
                'deskripsi'    => 'Pemecahan kontrak untuk menghindari pelelangan',
                'alternatif_rekom' => [5, 6, 9, 12],
            ],
            [
                'kode'         => '1.04.05',
                'kode_numerik' => '1.04.05',
                'kel'          => 1,
                'sub_kel'      => 4,
                'jenis'        => 5,
                'kelompok'     => 'Temuan Ketidakpatuhan Terhadap Peraturan',
                'sub_kelompok' => 'Administrasi',
                'deskripsi'    => 'Pelaksanaan lelang secara performa',
                'alternatif_rekom' => [5, 9, 12],
            ],
            [
                'kode'         => '1.04.06',
                'kode_numerik' => '1.04.06',
                'kel'          => 1,
                'sub_kel'      => 4,
                'jenis'        => 6,
                'kelompok'     => 'Temuan Ketidakpatuhan Terhadap Peraturan',
                'sub_kelompok' => 'Administrasi',
                'deskripsi'    => 'Penyimpangan terhadap peraturan perundang-undangan bidang pengelolaan perlengkapan atau barang milik negara/daerah/perusahaan',
                'alternatif_rekom' => [4, 5, 6, 9, 13],
            ],
            [
                'kode'         => '1.04.07',
                'kode_numerik' => '1.04.07',
                'kel'          => 1,
                'sub_kel'      => 4,
                'jenis'        => 7,
                'kelompok'     => 'Temuan Ketidakpatuhan Terhadap Peraturan',
                'sub_kelompok' => 'Administrasi',
                'deskripsi'    => 'Penyimpangan terhadap peraturan perundang-undangan bidang tertentu lainnya seperti kehutanan, pertambangan, perpajakan, dll',
                'alternatif_rekom' => [5, 9, 12],
            ],
            [
                'kode'         => '1.04.08',
                'kode_numerik' => '1.04.08',
                'kel'          => 1,
                'sub_kel'      => 4,
                'jenis'        => 8,
                'kelompok'     => 'Temuan Ketidakpatuhan Terhadap Peraturan',
                'sub_kelompok' => 'Administrasi',
                'deskripsi'    => 'Koreksi perhitungan subsidi/kewajiban pelayanan umum',
                'alternatif_rekom' => [6, 9],
            ],
            [
                'kode'         => '1.04.09',
                'kode_numerik' => '1.04.09',
                'kel'          => 1,
                'sub_kel'      => 4,
                'jenis'        => 9,
                'kelompok'     => 'Temuan Ketidakpatuhan Terhadap Peraturan',
                'sub_kelompok' => 'Administrasi',
                'deskripsi'    => 'Pembentukan cadangan piutang, perhitungan penyusutan atau amortisasi tidak sesuai ketentuan',
                'alternatif_rekom' => [5, 6, 9, 12],
            ],
            [
                'kode'         => '1.04.10',
                'kode_numerik' => '1.04.10',
                'kel'          => 1,
                'sub_kel'      => 4,
                'jenis'        => 10,
                'kelompok'     => 'Temuan Ketidakpatuhan Terhadap Peraturan',
                'sub_kelompok' => 'Administrasi',
                'deskripsi'    => 'Penyetoran penerimaan negara/daerah atau kas di bendaharawan ke kas negara/daerah melebihi batas waktu yang ditentukan',
                'alternatif_rekom' => [5, 9],
            ],
            [
                'kode'         => '1.04.11',
                'kode_numerik' => '1.04.11',
                'kel'          => 1,
                'sub_kel'      => 4,
                'jenis'        => 11,
                'kelompok'     => 'Temuan Ketidakpatuhan Terhadap Peraturan',
                'sub_kelompok' => 'Administrasi',
                'deskripsi'    => 'Pertanggungjawaban/penyetoran uang persediaan melebihi batas waktu yang ditentukan',
                'alternatif_rekom' => [5, 9],
            ],
            [
                'kode'         => '1.04.12',
                'kode_numerik' => '1.04.12',
                'kel'          => 1,
                'sub_kel'      => 4,
                'jenis'        => 12,
                'kelompok'     => 'Temuan Ketidakpatuhan Terhadap Peraturan',
                'sub_kelompok' => 'Administrasi',
                'deskripsi'    => 'Sisa kas di bendahara pengeluaran akhir tahun anggaran belum/tidak disetor ke kas negara/daerah',
                'alternatif_rekom' => [1, 5, 6, 9, 12],
            ],
            [
                'kode'         => '1.04.13',
                'kode_numerik' => '1.04.13',
                'kel'          => 1,
                'sub_kel'      => 4,
                'jenis'        => 13,
                'kelompok'     => 'Temuan Ketidakpatuhan Terhadap Peraturan',
                'sub_kelompok' => 'Administrasi',
                'deskripsi'    => 'Pengeluaran investasi pemerintah tidak didukung bukti yang sah',
                'alternatif_rekom' => [5, 6, 9, 12],
            ],
            [
                'kode'         => '1.04.14',
                'kode_numerik' => '1.04.14',
                'kel'          => 1,
                'sub_kel'      => 4,
                'jenis'        => 14,
                'kelompok'     => 'Temuan Ketidakpatuhan Terhadap Peraturan',
                'sub_kelompok' => 'Administrasi',
                'deskripsi'    => 'Kepemilikan aset tidak/belum didukung bukti yang sah',
                'alternatif_rekom' => [5, 6, 9, 12],
            ],
            [
                'kode'         => '1.04.15',
                'kode_numerik' => '1.04.15',
                'kel'          => 1,
                'sub_kel'      => 4,
                'jenis'        => 15,
                'kelompok'     => 'Temuan Ketidakpatuhan Terhadap Peraturan',
                'sub_kelompok' => 'Administrasi',
                'deskripsi'    => 'Pengalihan anggaran antar MAK tidak sah',
                'alternatif_rekom' => [5, 9],
            ],
            [
                'kode'         => '1.04.16',
                'kode_numerik' => '1.04.16',
                'kel'          => 1,
                'sub_kel'      => 4,
                'jenis'        => 16,
                'kelompok'     => 'Temuan Ketidakpatuhan Terhadap Peraturan',
                'sub_kelompok' => 'Administrasi',
                'deskripsi'    => 'Pelampauan pagu anggaran',
                'alternatif_rekom' => [5, 6, 9, 12],
            ],

            // ── Sub Kelompok 05: Indikasi Tindak Pidana ──────────────────
            [
                'kode'         => '1.05.01',
                'kode_numerik' => '1.05.01',
                'kel'          => 1,
                'sub_kel'      => 5,
                'jenis'        => 1,
                'kelompok'     => 'Temuan Ketidakpatuhan Terhadap Peraturan',
                'sub_kelompok' => 'Indikasi tindak pidana',
                'deskripsi'    => 'Indikasi tindak pidana korupsi',
                'alternatif_rekom' => [5, 11, 12],
            ],
            [
                'kode'         => '1.05.02',
                'kode_numerik' => '1.05.02',
                'kel'          => 1,
                'sub_kel'      => 5,
                'jenis'        => 2,
                'kelompok'     => 'Temuan Ketidakpatuhan Terhadap Peraturan',
                'sub_kelompok' => 'Indikasi tindak pidana',
                'deskripsi'    => 'Indikasi tindak pidana perbankan',
                'alternatif_rekom' => [5, 11, 12],
            ],
            [
                'kode'         => '1.05.03',
                'kode_numerik' => '1.05.03',
                'kel'          => 1,
                'sub_kel'      => 5,
                'jenis'        => 3,
                'kelompok'     => 'Temuan Ketidakpatuhan Terhadap Peraturan',
                'sub_kelompok' => 'Indikasi tindak pidana',
                'deskripsi'    => 'Indikasi tindak pidana perpajakan',
                'alternatif_rekom' => [5, 11, 12],
            ],
            [
                'kode'         => '1.05.04',
                'kode_numerik' => '1.05.04',
                'kel'          => 1,
                'sub_kel'      => 5,
                'jenis'        => 4,
                'kelompok'     => 'Temuan Ketidakpatuhan Terhadap Peraturan',
                'sub_kelompok' => 'Indikasi tindak pidana',
                'deskripsi'    => 'Indikasi tindak pidana kepabeanan',
                'alternatif_rekom' => [5, 11, 12],
            ],
            [
                'kode'         => '1.05.05',
                'kode_numerik' => '1.05.05',
                'kel'          => 1,
                'sub_kel'      => 5,
                'jenis'        => 5,
                'kelompok'     => 'Temuan Ketidakpatuhan Terhadap Peraturan',
                'sub_kelompok' => 'Indikasi tindak pidana',
                'deskripsi'    => 'Indikasi tindak pidana kehutanan',
                'alternatif_rekom' => [5, 11, 12],
            ],
            [
                'kode'         => '1.05.06',
                'kode_numerik' => '1.05.06',
                'kel'          => 1,
                'sub_kel'      => 5,
                'jenis'        => 6,
                'kelompok'     => 'Temuan Ketidakpatuhan Terhadap Peraturan',
                'sub_kelompok' => 'Indikasi tindak pidana',
                'deskripsi'    => 'Indikasi tindak pidana pasar modal',
                'alternatif_rekom' => [5, 11, 12],
            ],
            [
                'kode'         => '1.05.07',
                'kode_numerik' => '1.05.07',
                'kel'          => 1,
                'sub_kel'      => 5,
                'jenis'        => 7,
                'kelompok'     => 'Temuan Ketidakpatuhan Terhadap Peraturan',
                'sub_kelompok' => 'Indikasi tindak pidana',
                'deskripsi'    => 'Indikasi tindak pidana khusus lainnya',
                'alternatif_rekom' => [5, 11, 12],
            ],

            // ════════════════════════════════════════════════════════════════
            // KELOMPOK 2 — TEMUAN KELEMAHAN SISTEM PENGENDALIAN INTERN (SPI)
            // ════════════════════════════════════════════════════════════════

            // ── Sub Kelompok 01: SPI Akuntansi & Pelaporan ───────────────
            [
                'kode'         => '2.01.01',
                'kode_numerik' => '2.01.01',
                'kel'          => 2,
                'sub_kel'      => 1,
                'jenis'        => 1,
                'kelompok'     => 'Temuan Kelemahan Sistem Pengendalian Intern',
                'sub_kelompok' => 'Kelemahan sistem pengendalian akuntansi dan pelaporan',
                'deskripsi'    => 'Pencatatan tidak/belum dilakukan atau tidak akurat',
                'alternatif_rekom' => [5, 6, 7],
            ],
            [
                'kode'         => '2.01.02',
                'kode_numerik' => '2.01.02',
                'kel'          => 2,
                'sub_kel'      => 1,
                'jenis'        => 2,
                'kelompok'     => 'Temuan Kelemahan Sistem Pengendalian Intern',
                'sub_kelompok' => 'Kelemahan sistem pengendalian akuntansi dan pelaporan',
                'deskripsi'    => 'Proses penyusunan laporan tidak sesuai ketentuan',
                'alternatif_rekom' => [5, 6, 13],
            ],
            [
                'kode'         => '2.01.03',
                'kode_numerik' => '2.01.03',
                'kel'          => 2,
                'sub_kel'      => 1,
                'jenis'        => 3,
                'kelompok'     => 'Temuan Kelemahan Sistem Pengendalian Intern',
                'sub_kelompok' => 'Kelemahan sistem pengendalian akuntansi dan pelaporan',
                'deskripsi'    => 'Entitas terlambat menyampaikan laporan',
                'alternatif_rekom' => [5, 6],
            ],
            [
                'kode'         => '2.01.04',
                'kode_numerik' => '2.01.04',
                'kel'          => 2,
                'sub_kel'      => 1,
                'jenis'        => 4,
                'kelompok'     => 'Temuan Kelemahan Sistem Pengendalian Intern',
                'sub_kelompok' => 'Kelemahan sistem pengendalian akuntansi dan pelaporan',
                'deskripsi'    => 'Sistem informasi akuntansi dan pelaporan tidak memadai',
                'alternatif_rekom' => [7, 13],
            ],
            [
                'kode'         => '2.01.05',
                'kode_numerik' => '2.01.05',
                'kel'          => 2,
                'sub_kel'      => 1,
                'jenis'        => 5,
                'kelompok'     => 'Temuan Kelemahan Sistem Pengendalian Intern',
                'sub_kelompok' => 'Kelemahan sistem pengendalian akuntansi dan pelaporan',
                'deskripsi'    => 'Sistem informasi akuntansi dan pelaporan belum didukung SDM yang memadai',
                'alternatif_rekom' => [8, 13],
            ],

            // ── Sub Kelompok 02: SPI Anggaran Pendapatan & Belanja ───────
            [
                'kode'         => '2.02.01',
                'kode_numerik' => '2.02.01',
                'kel'          => 2,
                'sub_kel'      => 2,
                'jenis'        => 1,
                'kelompok'     => 'Temuan Kelemahan Sistem Pengendalian Intern',
                'sub_kelompok' => 'Kelemahan sistem pengendalian pelaksanaan anggaran pendapatan dan belanja',
                'deskripsi'    => 'Perencanaan kegiatan tidak memadai',
                'alternatif_rekom' => [5, 9, 13],
            ],
            [
                'kode'         => '2.02.02',
                'kode_numerik' => '2.02.02',
                'kel'          => 2,
                'sub_kel'      => 2,
                'jenis'        => 2,
                'kelompok'     => 'Temuan Kelemahan Sistem Pengendalian Intern',
                'sub_kelompok' => 'Kelemahan sistem pengendalian pelaksanaan anggaran pendapatan dan belanja',
                'deskripsi'    => 'Mekanisme pemungutan, penyetoran dan pelaporan serta penggunaan penerimaan negara/daerah/perusahaan dan hibah tidak sesuai ketentuan',
                'alternatif_rekom' => [5, 9, 13],
            ],
            [
                'kode'         => '2.02.03',
                'kode_numerik' => '2.02.03',
                'kel'          => 2,
                'sub_kel'      => 2,
                'jenis'        => 3,
                'kelompok'     => 'Temuan Kelemahan Sistem Pengendalian Intern',
                'sub_kelompok' => 'Kelemahan sistem pengendalian pelaksanaan anggaran pendapatan dan belanja',
                'deskripsi'    => 'Penyimpangan terhadap peraturan perundang-undangan bidang teknis tertentu atau ketentuan intern organisasi yang diperiksa tentang pendapatan dan belanja',
                'alternatif_rekom' => [5, 9, 13],
            ],
            [
                'kode'         => '2.02.04',
                'kode_numerik' => '2.02.04',
                'kel'          => 2,
                'sub_kel'      => 2,
                'jenis'        => 4,
                'kelompok'     => 'Temuan Kelemahan Sistem Pengendalian Intern',
                'sub_kelompok' => 'Kelemahan sistem pengendalian pelaksanaan anggaran pendapatan dan belanja',
                'deskripsi'    => 'Pelaksanaan belanja di luar mekanisme APBN/APBD',
                'alternatif_rekom' => [7, 9],
            ],
            [
                'kode'         => '2.02.05',
                'kode_numerik' => '2.02.05',
                'kel'          => 2,
                'sub_kel'      => 2,
                'jenis'        => 5,
                'kelompok'     => 'Temuan Kelemahan Sistem Pengendalian Intern',
                'sub_kelompok' => 'Kelemahan sistem pengendalian pelaksanaan anggaran pendapatan dan belanja',
                'deskripsi'    => 'Penetapan/pelaksanaan kebijakan tidak tepat atau belum dilakukan berakibat hilangnya potensi penerimaan/pendapatan',
                'alternatif_rekom' => [5, 9, 11],
            ],
            [
                'kode'         => '2.02.06',
                'kode_numerik' => '2.02.06',
                'kel'          => 2,
                'sub_kel'      => 2,
                'jenis'        => 6,
                'kelompok'     => 'Temuan Kelemahan Sistem Pengendalian Intern',
                'sub_kelompok' => 'Kelemahan sistem pengendalian pelaksanaan anggaran pendapatan dan belanja',
                'deskripsi'    => 'Penetapan/pelaksanaan kebijakan tidak tepat atau belum dilakukan berakibat peningkatan biaya/belanja',
                'alternatif_rekom' => [5, 9, 11],
            ],
            [
                'kode'         => '2.02.07',
                'kode_numerik' => '2.02.07',
                'kel'          => 2,
                'sub_kel'      => 2,
                'jenis'        => 7,
                'kelompok'     => 'Temuan Kelemahan Sistem Pengendalian Intern',
                'sub_kelompok' => 'Kelemahan sistem pengendalian pelaksanaan anggaran pendapatan dan belanja',
                'deskripsi'    => 'Kelemahan pengelolaan fisik aset',
                'alternatif_rekom' => [5, 7, 9, 12],
            ],

            // ── Sub Kelompok 03: Kelemahan Struktur Pengendalian Intern ──
            [
                'kode'         => '2.03.01',
                'kode_numerik' => '2.03.01',
                'kel'          => 2,
                'sub_kel'      => 3,
                'jenis'        => 1,
                'kelompok'     => 'Temuan Kelemahan Sistem Pengendalian Intern',
                'sub_kelompok' => 'Kelemahan struktur pengendalian intern',
                'deskripsi'    => 'Entitas tidak memiliki SOP yang formal untuk suatu prosedur atau keseluruhan prosedur',
                'alternatif_rekom' => [9, 13],
            ],
            [
                'kode'         => '2.03.02',
                'kode_numerik' => '2.03.02',
                'kel'          => 2,
                'sub_kel'      => 3,
                'jenis'        => 2,
                'kelompok'     => 'Temuan Kelemahan Sistem Pengendalian Intern',
                'sub_kelompok' => 'Kelemahan struktur pengendalian intern',
                'deskripsi'    => 'SOP yang ada pada entitas tidak berjalan secara optimal atau tidak ditaati',
                'alternatif_rekom' => [5, 13],
            ],
            [
                'kode'         => '2.03.03',
                'kode_numerik' => '2.03.03',
                'kel'          => 2,
                'sub_kel'      => 3,
                'jenis'        => 3,
                'kelompok'     => 'Temuan Kelemahan Sistem Pengendalian Intern',
                'sub_kelompok' => 'Kelemahan struktur pengendalian intern',
                'deskripsi'    => 'Entitas tidak memiliki satuan pengawas intern',
                'alternatif_rekom' => [9, 10],
            ],
            [
                'kode'         => '2.03.04',
                'kode_numerik' => '2.03.04',
                'kel'          => 2,
                'sub_kel'      => 3,
                'jenis'        => 4,
                'kelompok'     => 'Temuan Kelemahan Sistem Pengendalian Intern',
                'sub_kelompok' => 'Kelemahan struktur pengendalian intern',
                'deskripsi'    => 'Satuan pengawas intern yang ada tidak memadai atau tidak berjalan optimal',
                'alternatif_rekom' => [5, 10],
            ],
            [
                'kode'         => '2.03.05',
                'kode_numerik' => '2.03.05',
                'kel'          => 2,
                'sub_kel'      => 3,
                'jenis'        => 5,
                'kelompok'     => 'Temuan Kelemahan Sistem Pengendalian Intern',
                'sub_kelompok' => 'Kelemahan struktur pengendalian intern',
                'deskripsi'    => 'Tidak ada pemisahan tugas dan fungsi yang memadai',
                'alternatif_rekom' => [9, 10],
            ],

            // ════════════════════════════════════════════════════════════════
            // KELOMPOK 3 — TEMUAN 3E (EKONOMIS, EFISIEN, EFEKTIF)
            // ════════════════════════════════════════════════════════════════

            // ── Sub Kelompok 01: Ketidakhematan ──────────────────────────
            [
                'kode'         => '3.01.01',
                'kode_numerik' => '3.01.01',
                'kel'          => 3,
                'sub_kel'      => 1,
                'jenis'        => 1,
                'kelompok'     => 'Temuan 3E',
                'sub_kelompok' => 'Ketidakhematan/pemborosan/ketidakekonomisan',
                'deskripsi'    => 'Pengadaan barang/jasa melebihi kebutuhan',
                'alternatif_rekom' => [5, 9],
            ],
            [
                'kode'         => '3.01.02',
                'kode_numerik' => '3.01.02',
                'kel'          => 3,
                'sub_kel'      => 1,
                'jenis'        => 2,
                'kelompok'     => 'Temuan 3E',
                'sub_kelompok' => 'Ketidakhematan/pemborosan/ketidakekonomisan',
                'deskripsi'    => 'Penetapan kualitas dan kuantitas barang/jasa yang digunakan tidak sesuai standar',
                'alternatif_rekom' => [5, 9, 13],
            ],
            [
                'kode'         => '3.01.03',
                'kode_numerik' => '3.01.03',
                'kel'          => 3,
                'sub_kel'      => 1,
                'jenis'        => 3,
                'kelompok'     => 'Temuan 3E',
                'sub_kelompok' => 'Ketidakhematan/pemborosan/ketidakekonomisan',
                'deskripsi'    => 'Pemborosan keuangan negara/daerah/perusahaan atau kemahalan harga',
                'alternatif_rekom' => [5, 9, 12],
            ],

            // ── Sub Kelompok 02: Ketidakefisienan ────────────────────────
            [
                'kode'         => '3.02.01',
                'kode_numerik' => '3.02.01',
                'kel'          => 3,
                'sub_kel'      => 2,
                'jenis'        => 1,
                'kelompok'     => 'Temuan 3E',
                'sub_kelompok' => 'Ketidakefisienan',
                'deskripsi'    => 'Penggunaan kuantitas input untuk satu satuan output lebih besar/tinggi dari yang seharusnya',
                'alternatif_rekom' => [5, 9, 13],
            ],
            [
                'kode'         => '3.02.02',
                'kode_numerik' => '3.02.02',
                'kel'          => 3,
                'sub_kel'      => 2,
                'jenis'        => 2,
                'kelompok'     => 'Temuan 3E',
                'sub_kelompok' => 'Ketidakefisienan',
                'deskripsi'    => 'Penggunaan kualitas input untuk satu satuan output lebih tinggi dari seharusnya',
                'alternatif_rekom' => [5, 9, 13],
            ],

            // ── Sub Kelompok 03: Ketidakefektifan ────────────────────────
            [
                'kode'         => '3.03.01',
                'kode_numerik' => '3.03.01',
                'kel'          => 3,
                'sub_kel'      => 3,
                'jenis'        => 1,
                'kelompok'     => 'Temuan 3E',
                'sub_kelompok' => 'Ketidakefektifan',
                'deskripsi'    => 'Penggunaan anggaran tidak tepat sasaran/tidak sesuai peruntukan',
                'alternatif_rekom' => [5, 9],
            ],
            [
                'kode'         => '3.03.02',
                'kode_numerik' => '3.03.02',
                'kel'          => 3,
                'sub_kel'      => 3,
                'jenis'        => 2,
                'kelompok'     => 'Temuan 3E',
                'sub_kelompok' => 'Ketidakefektifan',
                'deskripsi'    => 'Pemanfaatan barang/jasa dilakukan tidak sesuai dengan rencana yang ditetapkan',
                'alternatif_rekom' => [5, 9, 12],
            ],
            [
                'kode'         => '3.03.03',
                'kode_numerik' => '3.03.03',
                'kel'          => 3,
                'sub_kel'      => 3,
                'jenis'        => 3,
                'kelompok'     => 'Temuan 3E',
                'sub_kelompok' => 'Ketidakefektifan',
                'deskripsi'    => 'Barang yang dibeli belum/tidak dapat dimanfaatkan',
                'alternatif_rekom' => [5, 9, 11],
            ],
            [
                'kode'         => '3.03.04',
                'kode_numerik' => '3.03.04',
                'kel'          => 3,
                'sub_kel'      => 3,
                'jenis'        => 4,
                'kelompok'     => 'Temuan 3E',
                'sub_kelompok' => 'Ketidakefektifan',
                'deskripsi'    => 'Pemanfaatan barang/jasa tidak berdampak terhadap pencapaian tujuan organisasi',
                'alternatif_rekom' => [5, 9, 11],
            ],
            [
                'kode'         => '3.03.05',
                'kode_numerik' => '3.03.05',
                'kel'          => 3,
                'sub_kel'      => 3,
                'jenis'        => 5,
                'kelompok'     => 'Temuan 3E',
                'sub_kelompok' => 'Ketidakefektifan',
                'deskripsi'    => 'Pelaksanaan kegiatan terlambat/terhambat sehingga mempengaruhi pencapaian tujuan organisasi',
                'alternatif_rekom' => [5, 9, 11],
            ],
            [
                'kode'         => '3.03.06',
                'kode_numerik' => '3.03.06',
                'kel'          => 3,
                'sub_kel'      => 3,
                'jenis'        => 6,
                'kelompok'     => 'Temuan 3E',
                'sub_kelompok' => 'Ketidakefektifan',
                'deskripsi'    => 'Pelayanan kepada masyarakat tidak optimal',
                'alternatif_rekom' => [5, 8, 9, 11, 13],
            ],
            [
                'kode'         => '3.03.07',
                'kode_numerik' => '3.03.07',
                'kel'          => 3,
                'sub_kel'      => 3,
                'jenis'        => 7,
                'kelompok'     => 'Temuan 3E',
                'sub_kelompok' => 'Ketidakefektifan',
                'deskripsi'    => 'Fungsi atau tugas instansi yang diperiksa tidak diselenggarakan dengan baik termasuk target penerimaan tidak tercapai',
                'alternatif_rekom' => [5, 8, 9, 11, 13],
            ],
            [
                'kode'         => '3.03.08',
                'kode_numerik' => '3.03.08',
                'kel'          => 3,
                'sub_kel'      => 3,
                'jenis'        => 8,
                'kelompok'     => 'Temuan 3E',
                'sub_kelompok' => 'Ketidakefektifan',
                'deskripsi'    => 'Penggunaan biaya promosi/pemasaran tidak efektif',
                'alternatif_rekom' => [5, 9, 11],
            ],
        ];
    }
}