<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class UnitDiperiksaSeeder extends Seeder
{
    public function run(): void
    {
        $data = [
            // Sumber
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Sumber', 'nama_unit' => 'Desa Ronggomulyo'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Sumber', 'nama_unit' => 'Desa Logede'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Sumber', 'nama_unit' => 'Desa Pelemsari'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Sumber', 'nama_unit' => 'Desa Logung'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Sumber', 'nama_unit' => 'Desa Krikilan'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Sumber', 'nama_unit' => 'Desa Kedungtulup'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Sumber', 'nama_unit' => 'Desa Jatihadi'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Sumber', 'nama_unit' => 'Desa Polbayem'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Sumber', 'nama_unit' => 'Desa Sumber'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Sumber', 'nama_unit' => 'Desa Jadi'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Sumber', 'nama_unit' => 'Desa Grawan'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Sumber', 'nama_unit' => 'Desa Randuagung'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Sumber', 'nama_unit' => 'Desa Sukorejo'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Sumber', 'nama_unit' => 'Desa Tlogotunggal'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Sumber', 'nama_unit' => 'Desa Bogorejo'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Sumber', 'nama_unit' => 'Desa Megulung'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Sumber', 'nama_unit' => 'Desa Kedungasem'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Sumber', 'nama_unit' => 'Desa Sekarsari'],

            // Bulu
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Bulu', 'nama_unit' => 'Desa Mlatirejo'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Bulu', 'nama_unit' => 'Desa Sendangmulyo'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Bulu', 'nama_unit' => 'Desa Pondokrejo'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Bulu', 'nama_unit' => 'Desa Warugunung'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Bulu', 'nama_unit' => 'Desa Pinggan'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Bulu', 'nama_unit' => 'Desa Cabean'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Bulu', 'nama_unit' => 'Desa Lambangan Kulon'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Bulu', 'nama_unit' => 'Desa Lambangan Wetan'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Bulu', 'nama_unit' => 'Desa Sumbermulyo'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Bulu', 'nama_unit' => 'Desa Karangasem'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Bulu', 'nama_unit' => 'Desa Pasedan'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Bulu', 'nama_unit' => 'Desa Ngulaan'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Bulu', 'nama_unit' => 'Desa Jukung'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Bulu', 'nama_unit' => 'Desa Bulu'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Bulu', 'nama_unit' => 'Desa Mantingan'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Bulu', 'nama_unit' => 'Desa Kadiwono'],

            // Gunem
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Gunem', 'nama_unit' => 'Desa Kajar'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Gunem', 'nama_unit' => 'Desa Timbrangan'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Gunem', 'nama_unit' => 'Desa Tegaldowo'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Gunem', 'nama_unit' => 'Desa Pasucen'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Gunem', 'nama_unit' => 'Desa Suntri'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Gunem', 'nama_unit' => 'Desa Dowan'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Gunem', 'nama_unit' => 'Desa Trembes'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Gunem', 'nama_unit' => 'Desa Gunem'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Gunem', 'nama_unit' => 'Desa Kulutan'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Gunem', 'nama_unit' => 'Desa Sidomulyo'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Gunem', 'nama_unit' => 'Desa Telgawah'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Gunem', 'nama_unit' => 'Desa Sendangmulyo'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Gunem', 'nama_unit' => 'Desa Panohan'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Gunem', 'nama_unit' => 'Desa Demaan'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Gunem', 'nama_unit' => 'Desa Banyuurip'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Gunem', 'nama_unit' => 'Desa Sambongpayak'],

            // Sale
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Sale', 'nama_unit' => 'Desa Tahunan'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Sale', 'nama_unit' => 'Desa Ngajaran'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Sale', 'nama_unit' => 'Desa Mrayun'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Sale', 'nama_unit' => 'Desa Bancang'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Sale', 'nama_unit' => 'Desa Sale'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Sale', 'nama_unit' => 'Desa Joho'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Sale', 'nama_unit' => 'Desa Jinanten'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Sale', 'nama_unit' => 'Desa Gading'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Sale', 'nama_unit' => 'Desa Wonokerto'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Sale', 'nama_unit' => 'Desa Sumbermulyo'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Sale', 'nama_unit' => 'Desa Tengger'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Sale', 'nama_unit' => 'Desa Bitingan'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Sale', 'nama_unit' => 'Desa Pakis'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Sale', 'nama_unit' => 'Desa Ukir'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Sale', 'nama_unit' => 'Desa Rendeng'],

            // Sarang
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Sarang', 'nama_unit' => 'Desa Lodan Kulon'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Sarang', 'nama_unit' => 'Desa Lodan Wetan'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Sarang', 'nama_unit' => 'Desa Bonjor'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Sarang', 'nama_unit' => 'Desa Tawangrejo'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Sarang', 'nama_unit' => 'Desa Sampung'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Sarang', 'nama_unit' => 'Desa Baturno'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Sarang', 'nama_unit' => 'Desa Babaktulung'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Sarang', 'nama_unit' => 'Desa Nglojo'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Sarang', 'nama_unit' => 'Desa Jambangan'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Sarang', 'nama_unit' => 'Desa Pelang'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Sarang', 'nama_unit' => 'Desa Gilis'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Sarang', 'nama_unit' => 'Desa Gunungmulyo'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Sarang', 'nama_unit' => 'Desa Gonggang'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Sarang', 'nama_unit' => 'Desa Sumbermulyo'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Sarang', 'nama_unit' => 'Desa Kalipang'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Sarang', 'nama_unit' => 'Desa Dadapmulyo'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Sarang', 'nama_unit' => 'Desa Sendangmulyo'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Sarang', 'nama_unit' => 'Desa Banowan'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Sarang', 'nama_unit' => 'Desa Temperak'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Sarang', 'nama_unit' => 'Desa Karangmangu'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Sarang', 'nama_unit' => 'Desa Bajingjowo'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Sarang', 'nama_unit' => 'Desa Bajingmeduro'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Sarang', 'nama_unit' => 'Desa Sarangmeduro'],

            // Sedan
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Sedan', 'nama_unit' => 'Desa Ngulahan'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Sedan', 'nama_unit' => 'Desa Pacing'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Sedan', 'nama_unit' => 'Desa Karas'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Sedan', 'nama_unit' => 'Desa Mojosari'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Sedan', 'nama_unit' => 'Desa Gesikan'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Sedan', 'nama_unit' => 'Desa Sambiroto'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Sedan', 'nama_unit' => 'Desa Sedan'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Sedan', 'nama_unit' => 'Desa Karangasem'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Sedan', 'nama_unit' => 'Desa Sidorejo'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Sedan', 'nama_unit' => 'Desa Sidomulyo'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Sedan', 'nama_unit' => 'Desa Kedungringin'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Sedan', 'nama_unit' => 'Desa Gandrirojo'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Sedan', 'nama_unit' => 'Desa Candimulyo'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Sedan', 'nama_unit' => 'Desa Lemahputih'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Sedan', 'nama_unit' => 'Desa Kumbo'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Sedan', 'nama_unit' => 'Desa Dadapan'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Sedan', 'nama_unit' => 'Desa Sambong'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Sedan', 'nama_unit' => 'Desa Bogorejo'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Sedan', 'nama_unit' => 'Desa Kenongo'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Sedan', 'nama_unit' => 'Desa Jambeyan'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Sedan', 'nama_unit' => 'Desa Menoro'],

            // Pamotan
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Pamotan', 'nama_unit' => 'Desa Megal'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Pamotan', 'nama_unit' => 'Desa Ngemplakrejo'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Pamotan', 'nama_unit' => 'Desa Pragen'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Pamotan', 'nama_unit' => 'Desa Samaran'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Pamotan', 'nama_unit' => 'Desa Gambiran'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Pamotan', 'nama_unit' => 'Desa Bamban'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Pamotan', 'nama_unit' => 'Desa Bangunrejo'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Pamotan', 'nama_unit' => 'Desa Pamotan'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Pamotan', 'nama_unit' => 'Desa Sidorejo'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Pamotan', 'nama_unit' => 'Desa Tempaling'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Pamotan', 'nama_unit' => 'Desa Joho'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Pamotan', 'nama_unit' => 'Desa Mlagen'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Pamotan', 'nama_unit' => 'Desa Kepohagung'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Pamotan', 'nama_unit' => 'Desa Mlawat'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Pamotan', 'nama_unit' => 'Desa Segoromulyo'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Pamotan', 'nama_unit' => 'Desa Ketanggi'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Pamotan', 'nama_unit' => 'Desa Sendangagung'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Pamotan', 'nama_unit' => 'Desa Gegersimo'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Pamotan', 'nama_unit' => 'Desa Sumbangrejo'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Pamotan', 'nama_unit' => 'Desa Japerejo'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Pamotan', 'nama_unit' => 'Desa Tulung'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Pamotan', 'nama_unit' => 'Desa Ringin'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Pamotan', 'nama_unit' => 'Desa Sumberejo'],

            // Sulang
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Sulang', 'nama_unit' => 'Desa Tanjung'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Sulang', 'nama_unit' => 'Desa Kemadu'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Sulang', 'nama_unit' => 'Desa Sulang'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Sulang', 'nama_unit' => 'Desa Pomahan'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Sulang', 'nama_unit' => 'Desa Rukem'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Sulang', 'nama_unit' => 'Desa Korowelang'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Sulang', 'nama_unit' => 'Desa Karangharjo'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Sulang', 'nama_unit' => 'Desa Jatimudo'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Sulang', 'nama_unit' => 'Desa Kunir'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Sulang', 'nama_unit' => 'Desa Glebeg'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Sulang', 'nama_unit' => 'Desa Bogorame'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Sulang', 'nama_unit' => 'Desa Kaliombo'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Sulang', 'nama_unit' => 'Desa Sudo'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Sulang', 'nama_unit' => 'Desa Karangsari'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Sulang', 'nama_unit' => 'Desa Pragu'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Sulang', 'nama_unit' => 'Desa Kebonagung'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Sulang', 'nama_unit' => 'Desa Seren'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Sulang', 'nama_unit' => 'Desa Pranti'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Sulang', 'nama_unit' => 'Desa Pedak'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Sulang', 'nama_unit' => 'Desa Landoh'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Sulang', 'nama_unit' => 'Desa Kerep'],

            // Kaliori
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Kaliori', 'nama_unit' => 'Desa Meteseh'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Kaliori', 'nama_unit' => 'Desa Maguan'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Kaliori', 'nama_unit' => 'Desa Sidomulyo'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Kaliori', 'nama_unit' => 'Desa Wiroto'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Kaliori', 'nama_unit' => 'Desa Banggi'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Kaliori', 'nama_unit' => 'Desa Kuangsan'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Kaliori', 'nama_unit' => 'Desa Gunungsari'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Kaliori', 'nama_unit' => 'Desa Sendangagung'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Kaliori', 'nama_unit' => 'Desa Karangsekar'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Kaliori', 'nama_unit' => 'Desa Babadan'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Kaliori', 'nama_unit' => 'Desa Pengkol'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Kaliori', 'nama_unit' => 'Desa Sambiyan'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Kaliori', 'nama_unit' => 'Desa Mojorembun'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Kaliori', 'nama_unit' => 'Desa Tunggulsari'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Kaliori', 'nama_unit' => 'Desa Tambakagung'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Kaliori', 'nama_unit' => 'Desa Mojowarno'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Kaliori', 'nama_unit' => 'Desa Dresi Kulon'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Kaliori', 'nama_unit' => 'Desa Dresi Wetan'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Kaliori', 'nama_unit' => 'Desa Tasikharjo'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Kaliori', 'nama_unit' => 'Desa Purworejo'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Kaliori', 'nama_unit' => 'Desa Bogoharjo'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Kaliori', 'nama_unit' => 'Desa Banyudono'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Kaliori', 'nama_unit' => 'Desa Pantiharjo'],

            // Rembang
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Rembang', 'nama_unit' => 'Desa Kedungrejo'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Rembang', 'nama_unit' => 'Desa Turusgede'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Rembang', 'nama_unit' => 'Desa Kumendung'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Rembang', 'nama_unit' => 'Desa Sridadi'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Rembang', 'nama_unit' => 'Desa Padaran'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Rembang', 'nama_unit' => 'Desa Tlogomojo'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Rembang', 'nama_unit' => 'Desa Kasreman'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Rembang', 'nama_unit' => 'Desa Punjulharjo'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Rembang', 'nama_unit' => 'Desa Tritunggal'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Rembang', 'nama_unit' => 'Desa Pasarbanggi'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Rembang', 'nama_unit' => 'Desa Gedangan'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Rembang', 'nama_unit' => 'Desa Weton'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Rembang', 'nama_unit' => 'Desa Ngotet'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Rembang', 'nama_unit' => 'Desa Mondoteko'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Rembang', 'nama_unit' => 'Desa Ngadem'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Rembang', 'nama_unit' => 'Desa Ketanggi'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Rembang', 'nama_unit' => 'Desa Pulo'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Rembang', 'nama_unit' => 'Desa Waru'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Rembang', 'nama_unit' => 'Desa Magersari'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Rembang', 'nama_unit' => 'Desa Gegunung Kulon'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Rembang', 'nama_unit' => 'Desa Gegunung Wetan'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Rembang', 'nama_unit' => 'Desa Pacar'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Rembang', 'nama_unit' => 'Desa Tanjungsari'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Rembang', 'nama_unit' => 'Desa Sumberjo'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Rembang', 'nama_unit' => 'Desa Tasikagung'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Rembang', 'nama_unit' => 'Desa Sawahan'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Rembang', 'nama_unit' => 'Desa Leteh'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Rembang', 'nama_unit' => 'Desa Sidowayah'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Rembang', 'nama_unit' => 'Desa Kutoharjo'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Rembang', 'nama_unit' => 'Desa Pandean'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Rembang', 'nama_unit' => 'Desa Sukoharjo'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Rembang', 'nama_unit' => 'Desa Kabongan Lor'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Rembang', 'nama_unit' => 'Desa Kabongan Kidul'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Rembang', 'nama_unit' => 'Desa Tireman'],

            // Pancur
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Pancur', 'nama_unit' => 'Desa Japeledok'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Pancur', 'nama_unit' => 'Desa Jeruk'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Pancur', 'nama_unit' => 'Desa Doropayung'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Pancur', 'nama_unit' => 'Desa Karaskepoh'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Pancur', 'nama_unit' => 'Desa Tuyuhan'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Pancur', 'nama_unit' => 'Desa Pandan'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Pancur', 'nama_unit' => 'Desa Gemblengmulyo'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Pancur', 'nama_unit' => 'Desa Sumberagung'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Pancur', 'nama_unit' => 'Desa Kalitengah'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Pancur', 'nama_unit' => 'Desa Sidowayah'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Pancur', 'nama_unit' => 'Desa Kedung'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Pancur', 'nama_unit' => 'Desa Punggurharjo'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Pancur', 'nama_unit' => 'Desa Langkir'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Pancur', 'nama_unit' => 'Desa Pancur'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Pancur', 'nama_unit' => 'Desa Pohlandak'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Pancur', 'nama_unit' => 'Desa Warugunung'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Pancur', 'nama_unit' => 'Desa Criwik'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Pancur', 'nama_unit' => 'Desa Wuwur'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Pancur', 'nama_unit' => 'Desa Ngulangan'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Pancur', 'nama_unit' => 'Desa Banyuurip'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Pancur', 'nama_unit' => 'Desa Johogunung'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Pancur', 'nama_unit' => 'Desa Trenggulunan'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Pancur', 'nama_unit' => 'Desa Ngroto'],

            // Kragan
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Kragan', 'nama_unit' => 'Desa Tanjungsari'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Kragan', 'nama_unit' => 'Desa Sendangmulyo'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Kragan', 'nama_unit' => 'Desa Sendangwaru'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Kragan', 'nama_unit' => 'Desa Ngasinan'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Kragan', 'nama_unit' => 'Desa Kendalagung'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Kragan', 'nama_unit' => 'Desa Mojokerto'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Kragan', 'nama_unit' => 'Desa Tanjungan'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Kragan', 'nama_unit' => 'Desa Kebloran'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Kragan', 'nama_unit' => 'Desa Karanganyar'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Kragan', 'nama_unit' => 'Desa Karanglincak'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Kragan', 'nama_unit' => 'Desa Karangharjo'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Kragan', 'nama_unit' => 'Desa Kragan'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Kragan', 'nama_unit' => 'Desa Tegalmulyo'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Kragan', 'nama_unit' => 'Desa Balongmulyo'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Kragan', 'nama_unit' => 'Desa Narukan'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Kragan', 'nama_unit' => 'Desa Sudan'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Kragan', 'nama_unit' => 'Desa Terjan'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Kragan', 'nama_unit' => 'Desa Sendang'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Kragan', 'nama_unit' => 'Desa Watupecah'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Kragan', 'nama_unit' => 'Desa Woro'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Kragan', 'nama_unit' => 'Desa Sumurpule'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Kragan', 'nama_unit' => 'Desa Plawangan'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Kragan', 'nama_unit' => 'Desa Sumbergayam'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Kragan', 'nama_unit' => 'Desa Pandangan Wetan'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Kragan', 'nama_unit' => 'Desa Pandangan Kulon'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Kragan', 'nama_unit' => 'Desa Sumurtawang'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Kragan', 'nama_unit' => 'Desa Sumbersari'],

            // Sluke
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Sluke', 'nama_unit' => 'Desa Sanetan'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Sluke', 'nama_unit' => 'Desa Rakitan'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Sluke', 'nama_unit' => 'Desa Bendo'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Sluke', 'nama_unit' => 'Desa Labuhan Kidul'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Sluke', 'nama_unit' => 'Desa Sendangmulyo'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Sluke', 'nama_unit' => 'Desa Blimbing'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Sluke', 'nama_unit' => 'Desa Manggar'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Sluke', 'nama_unit' => 'Desa Jatisari'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Sluke', 'nama_unit' => 'Desa Langgar'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Sluke', 'nama_unit' => 'Desa Sluke'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Sluke', 'nama_unit' => 'Desa Jurangjero'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Sluke', 'nama_unit' => 'Desa Leran'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Sluke', 'nama_unit' => 'Desa Trahan'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Sluke', 'nama_unit' => 'Desa Pangkalan'],

            // Lasem
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Lasem', 'nama_unit' => 'Desa Karasgede'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Lasem', 'nama_unit' => 'Desa Jolotundo'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Lasem', 'nama_unit' => 'Desa Sumbergirang'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Lasem', 'nama_unit' => 'Desa Karangturi'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Lasem', 'nama_unit' => 'Desa Babagan'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Lasem', 'nama_unit' => 'Desa Dorokandang'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Lasem', 'nama_unit' => 'Desa Gedongmulyo'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Lasem', 'nama_unit' => 'Desa Dasun'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Lasem', 'nama_unit' => 'Desa Soditan'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Lasem', 'nama_unit' => 'Desa Ngemplak'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Lasem', 'nama_unit' => 'Desa Selopuro'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Lasem', 'nama_unit' => 'Desa Sendangcoyo'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Lasem', 'nama_unit' => 'Desa Ngargomulyo'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Lasem', 'nama_unit' => 'Desa Kajar'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Lasem', 'nama_unit' => 'Desa Gowak'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Lasem', 'nama_unit' => 'Desa Sendangasri'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Lasem', 'nama_unit' => 'Desa Tasiksono'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Lasem', 'nama_unit' => 'Desa Sriombo'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Lasem', 'nama_unit' => 'Desa Bonang'],
            ['kategori' => 'Desa', 'nama_kecamatan' => 'Lasem', 'nama_unit' => 'Desa Binangun'],
            //OPD
            ['kategori' => 'OPD', 'nama_kecamatan' => 'Rembang', 'nama_unit' => 'Bupati Rembang'],
            ['kategori' => 'OPD', 'nama_kecamatan' => 'Rembang', 'nama_unit' => 'Wakil Bupati Rembang'],
            ['kategori' => 'OPD', 'nama_kecamatan' => 'Rembang', 'nama_unit' => 'Sekretaris Daerah Kabupaten Rembang'],
            ['kategori' => 'OPD', 'nama_kecamatan' => 'Rembang', 'nama_unit' => 'Sekretaris Dewan Kabupaten Rembang'],
            ['kategori' => 'OPD', 'nama_kecamatan' => 'Rembang', 'nama_unit' => 'Kepala Dinas Pendidikan Pemuda dan Olah Raga Kabupaten Rembang'],
            ['kategori' => 'OPD', 'nama_kecamatan' => 'Rembang', 'nama_unit' => 'Kepala Dinas Kebudayaan dan Pariwisata Kabupaten Rembang'],
            ['kategori' => 'OPD', 'nama_kecamatan' => 'Rembang', 'nama_unit' => 'Kepala Dinas Perumahan dan Kawasan Permukiman Kabupaten Rembang'],
            ['kategori' => 'OPD', 'nama_kecamatan' => 'Rembang', 'nama_unit' => 'Kepala Dinas Lingkungan Hidup Kabupaten Rembang'],
            ['kategori' => 'OPD', 'nama_kecamatan' => 'Rembang', 'nama_unit' => 'Kepala Dinas Penanaman Modal Pelayanan Terpadu Satu Pintu Kabupaten Rembang'],
            ['kategori' => 'OPD', 'nama_kecamatan' => 'Rembang', 'nama_unit' => 'Kepala Dinas Kesehatan'],
            ['kategori' => 'OPD', 'nama_kecamatan' => 'Rembang', 'nama_unit' => 'Kepala Dinas Pekerjaan Umum dan Penataan Ruang Kabupaten Rembang'],
            ['kategori' => 'OPD', 'nama_kecamatan' => 'Rembang', 'nama_unit' => 'Kepala Dinas Perhubungan Kabupaten Rembang'],
            ['kategori' => 'OPD', 'nama_kecamatan' => 'Rembang', 'nama_unit' => 'Kepala Dinas Pemberdayaan Masyarakat dan Desa Kabupaten Rembang'],
            ['kategori' => 'OPD', 'nama_kecamatan' => 'Rembang', 'nama_unit' => 'Kepala Dinas Kelautan dan Perikanan Kabupaten Rembang'],
            ['kategori' => 'OPD', 'nama_kecamatan' => 'Rembang', 'nama_unit' => 'Kepala Badan Kesatuan Bangsa dan Politik Kabupaten Rembang'],
            ['kategori' => 'OPD', 'nama_kecamatan' => 'Rembang', 'nama_unit' => 'Kepala Dinas Komunikasi dan Informatika Kabupaten Rembang'],
            ['kategori' => 'OPD', 'nama_kecamatan' => 'Rembang', 'nama_unit' => 'Kepala Dinas Perdagangan, Koperasi dan UMKM Kabupaten Rembang'],
            ['kategori' => 'OPD', 'nama_kecamatan' => 'Rembang', 'nama_unit' => 'Kepala Dinas Kependudukan dan Pencatatan Sipil Kabupaten Rembang'],
            ['kategori' => 'OPD', 'nama_kecamatan' => 'Rembang', 'nama_unit' => 'Kepala Dinas Pertanian dan Pangan Kabupaten Rembang'],
            ['kategori' => 'OPD', 'nama_kecamatan' => 'Rembang', 'nama_unit' => 'Kepala Dinas Sosial, Pemberdayaan Perempuan dan Keluarga Berencana Kabupaten Rembang'],
            ['kategori' => 'OPD', 'nama_kecamatan' => 'Rembang', 'nama_unit' => 'Kepala Badan Perencanaan Pembangunan Daerah'],
            ['kategori' => 'OPD', 'nama_kecamatan' => 'Rembang', 'nama_unit' => 'Kepala Badan Pendapatan, Pengelolaan Keuangan dan Aset Daerah Kabupaten Rembang'],
            ['kategori' => 'OPD', 'nama_kecamatan' => 'Rembang', 'nama_unit' => 'Inspektur Inspektorat'],
            ['kategori' => 'OPD', 'nama_kecamatan' => 'Rembang', 'nama_unit' => 'Kepala Satuan Polisi Pamong Praja Kabupaten Rembang'],
            ['kategori' => 'OPD', 'nama_kecamatan' => 'Rembang', 'nama_unit' => 'Kepala Badan Kepegawaian Daerah Kabupaten Rembang'],
            ['kategori' => 'OPD', 'nama_kecamatan' => 'Rembang', 'nama_unit' => 'Kepala Pelaksana Badan Penanggulangan Bencana Daerah Kabupaten Rembang'],
            ['kategori' => 'OPD', 'nama_kecamatan' => 'Rembang', 'nama_unit' => 'Kepala Dinas Kearsipan dan Perpustakaan Kabupaten Rembang'],
            ['kategori' => 'OPD', 'nama_kecamatan' => 'Rembang', 'nama_unit' => 'Plt. Direktur RSUD R. Soetrasno Kabupaten Rembang'],
            ['kategori' => 'OPD', 'nama_kecamatan' => 'Rembang', 'nama_unit' => 'Kepala Dinas Perindustrian dan Tenaga Kerja Kabupaten Rembang'],

            ['kategori' => 'OPD', 'nama_kecamatan' => 'Sluke', 'nama_unit' => 'Camat Sluke'],
            ['kategori' => 'OPD', 'nama_kecamatan' => 'Sale', 'nama_unit' => 'Camat Sale'],
            ['kategori' => 'OPD', 'nama_kecamatan' => 'Bulu', 'nama_unit' => 'Camat Bulu'],
            ['kategori' => 'OPD', 'nama_kecamatan' => 'Lasem', 'nama_unit' => 'Camat Lasem'],
            ['kategori' => 'OPD', 'nama_kecamatan' => 'Pancur', 'nama_unit' => 'Camat Pancur'],
            ['kategori' => 'OPD', 'nama_kecamatan' => 'Sarang', 'nama_unit' => 'Camat Sarang'],
            ['kategori' => 'OPD', 'nama_kecamatan' => 'Sulang', 'nama_unit' => 'Camat Sulang'],
            ['kategori' => 'OPD', 'nama_kecamatan' => 'Kragan', 'nama_unit' => 'Camat Kragan'],
            ['kategori' => 'OPD', 'nama_kecamatan' => 'Sumber', 'nama_unit' => 'Camat Sumber'],
            ['kategori' => 'OPD', 'nama_kecamatan' => 'Pamotan', 'nama_unit' => 'Camat Pamotan'],
            ['kategori' => 'OPD', 'nama_kecamatan' => 'Gunem', 'nama_unit' => 'Camat Gunem'],
            ['kategori' => 'OPD', 'nama_kecamatan' => 'Kaliori', 'nama_unit' => 'Camat Kaliori'],
            ['kategori' => 'OPD', 'nama_kecamatan' => 'Sedan', 'nama_unit' => 'Camat Sedan'],
            ['kategori' => 'OPD', 'nama_kecamatan' => 'Rembang', 'nama_unit' => 'Camat Rembang'],


        ];

        // Insert bulk
        DB::table('unit_diperiksas')->insert($data);
    }
}